#!/bin/sh
#BSUB -J "makecorr[17-115]"
#BSUB -q week
#BSUB -R RH5
# These are necessary due to high memory requirements of correlation matrices
#BSUB -R "span[ptile=4]"
#BSUB -n 4
#BSUB -oo "makecorr%I.out"
/nas02/apps/matlab-2010a/matlab -nodisplay -nojvm -nosplash -r create_corr_matrices